language: objective-c
git:
  depth: 2
node_js:
  - "0.10"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
  - cd ..
  - npm install -g cordova-paramedic
  - npm install -g cordova
  - npm install -g ios-sim
script:
  - cordova-paramedic --platform ios --plugin ${TRAVIS_BUILD_DIR}
